apiVersion: v1
kind: Service
metadata:
  name: dintelli-backend-service
spec:
  selector:
    app: dintelli-backend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5007
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dintelli-backend
spec:
  selector:
    matchLabels:
      app: dintelli-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: dintelli-backend
    spec:
      containers:
        - name: dintelli-backend
          image: samyakinfotech/dintelli-combined-apis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5007
      imagePullSecrets:
        - name: samyak-registry
