name: python-app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: install dependencies
      run: make install
    - name: test app.py
      run: make test
    - name: format app.py
      run: make format
